Resources:
    Table:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ${self:service.name}-dynamodb
            AttributeDefinitions:
                - AttributeName: user_id
                  AttributeType: S
                - AttributeName: film_id
                  AttributeType: S
            KeySchema:
                - AttributeName: user_id
                  KeyType: HASH
                - AttributeName: film_id
                  KeyType: RANGE
            BillingMode: PAY_PER_REQUEST
